name: Effects
main: dev.esophose.playerparticles.PlayerParticles
version: '@version@'
api-version: '1.13'
description: A fun effects plugin forked for Overcast Community
author: Esophose
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit, PGM]
commands:
  fx:
    description: The main Effects command. By default, opens the GUI.
    permission: playerparticles.command
  fxo:
    description: Allows executing a /fx command for another player.
    permission: playerparticles.command.force

